{
 "title": "RIS demo PUT EuCNC",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Current RIS #1 pattern",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "selected_pattern_png_info{ris_id=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current RIS #2 pattern",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "selected_pattern_png_info{ris_id=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "canvas",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "selected_pattern_index", "legendFormat": "__auto" },
    { "expr": "rx_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Selected Pattern",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "selected_pattern", "legendFormat": "{{ris_0}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rx_power_by_pattern", "legendFormat": "{{ris_0}}" }
   ]
  },
  {
   "title": "Received power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    { "expr": "rx_power", "legendFormat": "Current" },
    { "expr": "avg_over_time(rx_power[10s])", "legendFormat": "Average in time" }
   ]
  }
 ]
}